version: "3"

services:
  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/root/.caddy
      - ./src/frontend/dist:/var/www/html/crowdlabel
    networks:
        - web

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web

networks:
  web:
    driver: bridge