version: "3"

services:
  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src/frontend/dist:/var/www/html/dist
    networks:
        - web

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge